### ISSUE TITLE
Find method throw exception when entry not find

### ISSUE THREAD

**Issue by leeaee** [actframework/act-eclipselink#4]
When not find any entities, JPA will throw an exception:
```log
javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.
	at org.eclipse.persistence.internal.jpa.QueryImpl.throwNoResultException(QueryImpl.java:983)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:533)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:402)
	at act.db.jpa.JPAQuery.first(JPAQuery.java:141)
	at act.db.jpa.JPADao.findOneBy(JPADao.java:101)
```
Can act unify this kind of return for ebean and JPA?

**Comment by greenlaw110** [comment]
@leeaee please report the version of act-eclipselink and actframework

**Comment by leeaee** [comment]
The issue appear in org.actframework:act-eclipselink:1.4.0, org.actframework:act-jpa-common:1.4.0
I find it was fixed in org.actframework:act-eclipselink:1.5.1
